import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Attempt to import geopandas, handle failure later
try:
    import geopandas as gpd

    GEOPANDAS_AVAILABLE = True
except ImportError:
    GEOPANDAS_AVAILABLE = False

print("--- Script started. Loading libraries, please wait... ---")

# ==============================================================================
# --- 1. Configuration ---
# ==============================================================================

# Directory for the baseline scenario results, generated by run_best_parameters.py
BASELINE_RESULTS_DIR = 'baseline_results'

# Directory for the optimized scenario results, generated by run_best_parameters.py
OPTIMIZED_RESULTS_DIR = 'optuna_study_results_congestion_MSA/results_trial_36'

# Output directory for all analysis plots and tables
PLOTS_OUTPUT_DIR = "Bayesian_Search"

# Filepath for the network GeoJSON, required for spatial analysis
NETWORK_GEOJSON_PATH = "network.geojson"
# Column name in the GeoJSON that matches the edge ID
EDGE_ID_COLUMN_IN_GEOJSON = "uniqueid"

# --- Spatial Plotting Mode ---
# 'final_only': Generates only the final summary maps (Faster, recommended)
# 'full':       Generates maps for every iteration plus a combined grid plot (Slower, more detailed)
SPATIAL_PLOT_MODE = 'final_only'


# ==============================================================================
# --- 2. Plotting and Analysis Functions ---
# ==============================================================================

def plot_convergence(optimized_dir: str):
    """
    Generates separate convergence plots for the objective function, total revenue, and total congestion.
    """
    print(f"--- (1/3) Generating Convergence Plots for '{optimized_dir}' ---")
    summary_file = os.path.join(optimized_dir, 'optimization_summary.csv')
    if not os.path.exists(summary_file):
        print(f"  ERROR: Summary file not found at '{summary_file}'. Skipping.")
        return

    scenario_name = os.path.basename(optimized_dir)
    scenario_plot_dir = os.path.join(PLOTS_OUTPUT_DIR, "1_Convergence_Plots")
    os.makedirs(scenario_plot_dir, exist_ok=True)
    summary_df = pd.read_csv(summary_file)
    sns.set_theme(style="whitegrid")

    # Plot 1: Objective Function
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=summary_df, x='iteration', y='objective', marker='s', linestyle='--')
    plt.title(f'Convergence of Objective Function\n({scenario_name})', fontsize=16)
    plt.xlabel('Iteration', fontsize=14)
    plt.ylabel('Objective Function Value', fontsize=14)
    output_filename = os.path.join(scenario_plot_dir, f'{scenario_name}_convergence_objective.png')
    plt.savefig(output_filename, dpi=300)
    plt.close()

    # Plot 2: Total Revenue
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=summary_df, x='iteration', y='revenue', color='g', marker='o')
    plt.title(f'Convergence of Total Revenue\n({scenario_name})', fontsize=16)
    plt.xlabel('Iteration', fontsize=14)
    plt.ylabel('Total Revenue ($)', fontsize=14)
    output_filename = os.path.join(scenario_plot_dir, f'{scenario_name}_convergence_revenue.png')
    plt.savefig(output_filename, dpi=300)
    plt.close()

    # Plot 3: Total Congestion
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=summary_df, x='iteration', y='congestion', color='r', marker='o')
    plt.title(f'Convergence of Total Congestion\n({scenario_name})', fontsize=16)
    plt.xlabel('Iteration', fontsize=14)
    plt.ylabel('Total Congestion (vehicle-seconds)', fontsize=14)
    output_filename = os.path.join(scenario_plot_dir, f'{scenario_name}_convergence_congestion.png')
    plt.savefig(output_filename, dpi=300)
    plt.close()
    print(f"  SUCCESS: Convergence plots saved to '{scenario_plot_dir}'\n")


def create_comparison_table(baseline_dir: str, optimized_dir: str):
    """
    Generates a performance comparison table for the optimized scenario vs. the baseline.
    """
    print(f"--- (2/3) Generating Performance Comparison Table for '{optimized_dir}' ---")
    baseline_summary_file = os.path.join(baseline_dir, 'optimization_summary.csv')
    optimized_summary_file = os.path.join(optimized_dir, 'optimization_summary.csv')

    if not os.path.exists(baseline_summary_file):
        print(f"  ERROR: Baseline summary file not found at '{baseline_summary_file}'. Skipping.")
        return
    if not os.path.exists(optimized_summary_file):
        print(f"  ERROR: Optimized summary file not found at '{optimized_summary_file}'. Skipping.")
        return

    baseline_series = pd.read_csv(baseline_summary_file).iloc[0]
    optimized_series = pd.read_csv(optimized_summary_file).iloc[-1]

    revenue_change = ((optimized_series['revenue'] - baseline_series['revenue']) / baseline_series['revenue']) * 100 if \
    baseline_series['revenue'] != 0 else float('inf')
    congestion_change = ((optimized_series['congestion'] - baseline_series['congestion']) / baseline_series[
        'congestion']) * 100 if baseline_series['congestion'] != 0 else float('-inf')

    comparison_data = {
        'Metric': ['Total Revenue ($)', 'Total Congestion (vehicle-seconds)'],
        'Baseline (No-Toll)': [f"{baseline_series['revenue']:,.2f}", f"{baseline_series['congestion']:,.0f}"],
        'Optimized Tolls': [f"{optimized_series['revenue']:,.2f}", f"{optimized_series['congestion']:,.0f}"],
        'Change (%)': [f"+{revenue_change:.2f}%" if revenue_change != float('inf') else "N/A (from zero)",
                       f"{congestion_change:.2f}%"]
    }
    comparison_df = pd.DataFrame(comparison_data)

    print("  SUCCESS: Performance comparison table generated.\n")
    print(comparison_df.to_string(index=False))

    table_dir = os.path.join(PLOTS_OUTPUT_DIR, "2_Performance_Comparison")
    os.makedirs(table_dir, exist_ok=True)
    output_filename = os.path.join(table_dir, 'performance_comparison.csv')
    comparison_df.to_csv(output_filename, index=False)
    print(f"\n  Comparison table saved to '{output_filename}'\n")


def plot_spatial_distribution(baseline_dir: str, optimized_dir: str, geojson_path: str, edge_id_col: str, mode: str):
    """
    Generates spatial distribution maps based on the selected mode.
    """
    print(f"--- (3/3) Generating Spatial Maps for '{optimized_dir}' (Mode: {mode}) ---")
    if not GEOPANDAS_AVAILABLE:
        print("  ERROR: Geopandas is not installed. Cannot generate spatial maps, skipping.")
        print("  You can install it by running: 'pip install geopandas'")
        return
    if not os.path.exists(geojson_path):
        print(f"  ERROR: Network GeoJSON file not found at '{geojson_path}'. Skipping.")
        return

    # --- Step 1: Load data ---
    network_gdf = gpd.read_file(geojson_path)
    baseline_details_file = os.path.join(baseline_dir, 'iteration_1_details.csv')
    optimized_summary_file = os.path.join(optimized_dir, 'optimization_summary.csv')

    if not (os.path.exists(baseline_details_file) and os.path.exists(optimized_summary_file)):
        print("  ERROR: Missing detailed data files for baseline or optimized scenario. Skipping.")
        return

    num_iterations = pd.read_csv(optimized_summary_file)['iteration'].max()
    baseline_df = pd.read_csv(baseline_details_file)

    # Load data for the required iterations based on the selected mode
    iterations_to_load = range(1, num_iterations + 1) if mode == 'full' else [num_iterations]

    iteration_gdfs = []
    for i in iterations_to_load:
        details_file = os.path.join(optimized_dir, f'iteration_{i}_details.csv')
        if not os.path.exists(details_file): continue
        iter_df = pd.read_csv(details_file)
        # Merge iteration data with baseline data to calculate congestion improvement
        merged_df = pd.merge(iter_df, baseline_df[['uniqueid', 'final_travel_time']], on='uniqueid',
                             suffixes=('_optim', '_base'))
        merged_df['congestion_reduction_s'] = merged_df['final_travel_time_base'] - merged_df['final_travel_time_optim']
        plot_gdf = network_gdf.merge(merged_df, left_on=edge_id_col, right_on='uniqueid', how='left')
        iteration_gdfs.append(plot_gdf)

    if not iteration_gdfs:
        print("  ERROR: No detailed iteration data found. Aborting spatial plots.")
        return

    # Establish global color scales to ensure all plots are comparable
    global_toll_max = pd.concat([gdf['toll_fee'].dropna() for gdf in iteration_gdfs]).max()
    all_reductions = pd.concat([gdf['congestion_reduction_s'].dropna() for gdf in iteration_gdfs])
    # Use quantiles to prevent extreme outliers from skewing the color scale
    max_abs_val = max(abs(all_reductions.quantile(0.05)), abs(all_reductions.quantile(0.95)))
    global_congestion_vmin, global_congestion_vmax = -max_abs_val, max_abs_val

    scenario_name = os.path.basename(optimized_dir)
    scenario_plot_dir = os.path.join(PLOTS_OUTPUT_DIR, "3_Spatial_Maps")
    os.makedirs(scenario_plot_dir, exist_ok=True)

    # --- Step 2: Plot final results (executed in all modes) ---
    print("  Generating spatial maps for the final iteration...")
    final_gdf = iteration_gdfs[-1]

    # Final Tolls Plot
    fig, ax = plt.subplots(1, 1, figsize=(15, 10))
    final_gdf.plot(column='toll_fee', ax=ax, legend=True, cmap='viridis', vmin=0, vmax=global_toll_max,
                   legend_kwds={'label': "Final Toll Fee ($)", 'orientation': "horizontal", 'pad': 0.05, 'shrink': 0.6})
    ax.set_title(f'Spatial Distribution of Final Tolls\n({scenario_name})', fontsize=16)
    ax.set_axis_off()
    output_filename = os.path.join(scenario_plot_dir, f'{scenario_name}_spatial_final_tolls.png')
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    plt.close(fig)

    # Final Congestion Reduction Plot
    fig, ax = plt.subplots(1, 1, figsize=(15, 10))
    final_gdf.plot(column='congestion_reduction_s', ax=ax, legend=True, cmap='RdYlGn', vmin=global_congestion_vmin,
                   vmax=global_congestion_vmax,
                   legend_kwds={'label': "Final Travel Time Reduction (s)", 'orientation': "horizontal", 'pad': 0.05,
                                'shrink': 0.6})
    ax.set_title(f'Spatial Distribution of Final Congestion Reduction (vs. Baseline)\n({scenario_name})', fontsize=16)
    ax.set_axis_off()
    output_filename = os.path.join(scenario_plot_dir, f'{scenario_name}_spatial_final_congestion_reduction.png')
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"  SUCCESS: Final results maps saved to '{scenario_plot_dir}'")

    # --- Step 3: If in 'full' mode, plot the detailed iteration evolution ---
    if mode == 'full' and len(iteration_gdfs) > 1:
        print("  Generating iteration evolution grid plots for 'full' mode...")
        # Adaptively adjust the grid layout
        n_items = len(iteration_gdfs)
        n_cols = 4
        n_rows = (n_items + n_cols - 1) // n_cols

        # Tolls Evolution Grid Plot
        fig_tolls, axes_tolls = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 5), sharex=True, sharey=True)
        axes_tolls = axes_tolls.flatten()
        fig_tolls.suptitle('Evolution of Tolls Across Iterations', fontsize=28, y=0.95)
        for i, ax in enumerate(axes_tolls):
            if i < n_items:
                plot_gdf = iteration_gdfs[i]
                plot_gdf.plot(column='toll_fee', cmap='viridis', vmin=0, vmax=global_toll_max, ax=ax, legend=False)
                ax.text(0.05, 0.9, f'Iter: {iterations_to_load[i]}', transform=ax.transAxes, fontsize=12, color='white',
                        bbox=dict(facecolor='black', alpha=0.5))
            ax.set_axis_off()
        # Add a single colorbar for the entire figure
        sm_toll = plt.cm.ScalarMappable(cmap='viridis', norm=plt.Normalize(vmin=0, vmax=global_toll_max))
        fig_tolls.colorbar(sm_toll, ax=axes_tolls, orientation='vertical', shrink=0.7, label='Toll Fee ($)')
        grid_output_path = os.path.join(scenario_plot_dir, f'{scenario_name}_GRID_spatial_tolls_evolution.png')
        plt.savefig(grid_output_path, dpi=300)
        plt.close(fig_tolls)
        print(f"  SUCCESS: Tolls evolution grid plot saved.")


# ==============================================================================
# --- 3. Main Execution ---
# ==============================================================================

def main():
    """Main function to execute all analysis and plotting tasks."""
    print("=========================================")
    print("===      STARTING BATCH ANALYSIS      ===")
    print(f"===    Output will be saved to: '{PLOTS_OUTPUT_DIR}'   ===")
    print(f"===    Spatial Plotting Mode: {SPATIAL_PLOT_MODE.upper()}      ===")
    print("=========================================\n")

    os.makedirs(PLOTS_OUTPUT_DIR, exist_ok=True)

    if not os.path.isdir(OPTIMIZED_RESULTS_DIR) or not os.path.isdir(BASELINE_RESULTS_DIR):
        print(f"FATAL ERROR: Input data directories not found.")
        print(f"Please ensure both '{BASELINE_RESULTS_DIR}' and '{OPTIMIZED_RESULTS_DIR}' exist.")
        print("Run the `run_best_parameters.py` script first to generate this data.")
        return

    # Sequentially execute each analysis task
    plot_convergence(OPTIMIZED_RESULTS_DIR)
    create_comparison_table(BASELINE_RESULTS_DIR, OPTIMIZED_RESULTS_DIR)
    plot_spatial_distribution(
        BASELINE_RESULTS_DIR,
        OPTIMIZED_RESULTS_DIR,
        NETWORK_GEOJSON_PATH,
        EDGE_ID_COLUMN_IN_GEOJSON,
        mode=SPATIAL_PLOT_MODE
    )

    print("\n=========================================")
    print("===      ALL ANALYSIS TASKS COMPLETE    ===")
    print("=========================================")


if __name__ == "__main__":
    main()