steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/blissful-jet-303616/manta:$TAG_NAME"
      - "-t"
      - "gcr.io/blissful-jet-303616/manta:latest"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/blissful-jet-303616/manta:$TAG_NAME"
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/blissful-jet-303616/manta:latest"
timeout: 7200s
images:
  - "gcr.io/blissful-jet-303616/manta:$TAG_NAME"
  - "gcr.io/blissful-jet-303616/manta:latest"
